// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAybUW3PQncQgTDGUrvTmKDX-mSB9Zbig',
    appId: '1:842671450266:android:eeafb9b4245f4ec84b5723',
    messagingSenderId: '842671450266',
    projectId: 'rallyclubapp',
    storageBucket: 'rallyclubapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnigjCpsJW_pxznLwcde0cpY94wLwmpFk',
    appId: '1:842671450266:ios:228b5f50721c69de4b5723',
    messagingSenderId: '842671450266',
    projectId: 'rallyclubapp',
    storageBucket: 'rallyclubapp.firebasestorage.app',
    iosBundleId: 'com.example.rallyClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnigjCpsJW_pxznLwcde0cpY94wLwmpFk',
    appId: '1:842671450266:ios:228b5f50721c69de4b5723',
    messagingSenderId: '842671450266',
    projectId: 'rallyclubapp',
    storageBucket: 'rallyclubapp.firebasestorage.app',
    iosBundleId: 'com.example.rallyClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgACQHAS9hKEtU5f4ToPkvOlQ06E2Dpuw',
    appId: '1:842671450266:web:5b1bc86d33ea871b4b5723',
    messagingSenderId: '842671450266',
    projectId: 'rallyclubapp',
    authDomain: 'rallyclubapp.firebaseapp.com',
    storageBucket: 'rallyclubapp.firebasestorage.app',
    measurementId: 'G-SVF952HPDJ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgACQHAS9hKEtU5f4ToPkvOlQ06E2Dpuw',
    appId: '1:842671450266:web:5b1bc86d33ea871b4b5723',
    messagingSenderId: '842671450266',
    projectId: 'rallyclubapp',
    authDomain: 'rallyclubapp.firebaseapp.com',
    storageBucket: 'rallyclubapp.firebasestorage.app',
    measurementId: 'G-SVF952HPDJ',
  );
}
